version: '3.8'

services:
  db:
    container_name: myproject_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend_network

  backend:
    build: ./myproject
    volumes:
      - ./myproject:/app
      - static_volume:/app/staticfiles  # Changed to match STATIC_ROOT
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: >
      bash -c "pip install -r requirements.txt &&
               python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               daphne -b 0.0.0.0 -p 8000 myproject.asgi:application"
    restart: always
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    command: sh -c "pnpm install && pnpm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # - static_volume:/app/public/static  # Mount static files for frontend access
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/static  # Changed path
      - media_volume:/var/www/media    # Changed path
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - backend_network

volumes:
  postgres_data:
  static_volume:    # Volume for static files
  media_volume:     # Volume for media files

networks:
  backend_network:
    driver: bridge