# prometheus/postgres_queries.yml
basic_stats:
  query: |
    SELECT
      current_database() as datname,
      count(*) as active_backends
    FROM pg_stat_activity
    WHERE state = 'active'
    GROUP BY 1;
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - active_backends:
        usage: "GAUGE"
        description: "Number of active backends"

database_stats:
  query: |
    SELECT
      datname,
      pg_database_size(datname) as size_bytes
    FROM pg_database
    WHERE datname = current_database();
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - size_bytes:
        usage: "GAUGE"
        description: "Database size in bytes"

table_stats:
  query: |
    SELECT
      schemaname,
      relname,
      n_live_tup as row_count,
      n_dead_tup as dead_rows
    FROM pg_stat_user_tables;
  metrics:
    - schemaname:
        usage: "LABEL"
        description: "Schema name"
    - relname:
        usage: "LABEL"
        description: "Table name"
    - row_count:
        usage: "GAUGE"
        description: "Number of live rows"
    - dead_rows:
        usage: "GAUGE"
        description: "Number of dead rows"