global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

# Add alerting rules
rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'nextjs_frontend'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']